name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - develop 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_SECRET}}
          heroku_app_name: "rs-projector" 
          heroku_email: "3461995@gmail.com"
          buildpack: mars/create-react-app-buildpack
          branch: "develop"